### ISSUE TITLE
请教~~~~~~~~~~~~~

### ISSUE THREAD

**Issue by xinzhongyouhai** [qzz0518/nexus-run#3]
===== Connecting to Nexus Network...

Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 1). Retrying in 2 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 2). Retrying in 4 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 3). Retrying in 8 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 4). Retrying in 16 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 5). Retrying in 32 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 6). Retrying in 64 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)
Could not connect to orchestrator (attempt 7). Retrying in 64 seconds...
Failed to connect to orchestrator at wss://beta.orchestrator.nexus.xyz:443/prove: TLS error: native-tls error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)

这个是什么原因

**Comment by qzz0518** [comment]
使用新版本
