### ISSUE TITLE
请教下 这种情况什么原因引起的？

### ISSUE THREAD

**Issue by xinzhongyouhai** [qzz0518/nexus-run#5]
![微信截图_20241213200941](https://github.com/user-attachments/assets/a732ae35-529e-4516-8e9f-30dd8ef50f04)
画面卡在这~不动~CPU低占用没有变化

**Comment by xinzhongyouhai** [comment]
有什么解决的办法~请教下~

**Comment by qzz0518** [comment]
> 有什么解决的办法~请教下~

项目方那边服务的问题。你可以尝试更换一个使用过的proveId或者尝试使用其他地域的IP启动。

**Comment by xinzhongyouhai** [comment]
> > 有什么解决的办法~请教下~
> 
> 项目方那边服务的问题。你可以尝试更换一个使用过的proveId或者尝试使用其他地域的IP启动。

感谢解答~~~
